x-airflow-common:
  &airflow-common
  build: .
  image: custom-airflow:latest
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    _PIP_ADDITIONAL_REQUIREMENTS: "kafka-python==2.0.2 ${_PIP_ADDITIONAL_REQUIREMENTS:-}"

  volumes:
    - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
    # - ${AIRFLOW_PROJ_DIR:-.}/config:/opt/airflow/config
    - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
    - ${AIRFLOW_PROJ_DIR:-.}/script/entrypoint.sh:/opt/airflow/script/entrypoint.sh
    - ${AIRFLOW_PROJ_DIR:-.}/requirements.txt:/opt/airflow/requirements.txt
    - ${AIRFLOW_PROJ_DIR:-.}/pipelines:/opt/airflow/pipelines
    - ${AIRFLOW_PROJ_DIR:-.}/constants:/opt/airflow/constants

  user: "${AIRFLOW_UID:-50000}:0"

  depends_on:
    &airflow-common-depends-on
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - realtimeflow

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    entrypoint: ['/opt/airflow/script/entrypoint.sh']
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - realtimeflow

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - realtimeflow

  airflow-triggerer:
    <<: *airflow-common
    command: triggerer
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully
    networks:
      - realtimeflow

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        mkdir -p /sources/logs /sources/dags /sources/plugins
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
        exec /entrypoint airflow version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      _PIP_ADDITIONAL_REQUIREMENTS: ''
    user: "0:0"
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}:/sources
    networks:
      - realtimeflow

  airflow-cli:
    <<: *airflow-common
    profiles:
      - debug
    environment:
      <<: *airflow-common-env
      CONNECTION_CHECK_MAX_COUNT: "0"
    command:
      - bash
      - -c
      - airflow
    networks:
      - realtimeflow

  broker:
    image: bitnami/kafka:3.7.1
    container_name: broker
    ports:
      - "9092:9092"
      - "9999:9999"
    environment:
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@localhost:9093"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://broker:9092"
      # JMX settings
      KAFKA_HEAP_OPTS: "-Xmx512m -Xms256m"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_JMX_PORT: "9999"
      KAFKA_JMX_HOSTNAME: "kafka-exporter"
      KAFKA_JMX_OPTS: "-Djava.rmi.server.hostname=broker -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=9999 -Dcom.sun.management.jmxremote.local.only=false"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 10s
      retries: 10
      start_period: 10s
    networks:
      - realtimeflow

  kafka-exporter:
    image: bitnami/jmx-exporter:0.19.0
    container_name: kafka-exporter
    ports:
      - "9101:9101"
    command:
      - "9101"
      - "/etc/jmx_exporter/kafka-metrics.yml"
    volumes:
      - ./volumes/jmx_exporter/kafka-metrics.yml:/etc/jmx_exporter/kafka-metrics.yml
    depends_on:
      - broker
    networks:
      - realtimeflow

  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:9092
    depends_on:
      - broker
    networks:
      - realtimeflow

  spark-master:
    build:
      context: .
      dockerfile: Dockerfile.spark
    image: custom-spark:latest
    container_name: spark-master
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"
      - "9094:9094"
      - "7203:7203"
    environment:
      SPARK_MASTER_OPTS: "-Dspark.metrics.conf=/opt/spark/conf/metrics.properties -javaagent:/opt/spark/jmx_exporter/jmx_prometheus_javaagent.jar=9094:/opt/spark/jmx_exporter/config.yml -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=7203 -Dcom.sun.management.jmxremote.rmi.port=7203 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=spark-master"
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}/spark_streaming:/opt/spark/spark_streaming
      - ${AIRFLOW_PROJ_DIR:-.}/constants:/opt/spark/constants
      - ${AIRFLOW_PROJ_DIR:-.}/monitoring/spark/metrics.properties:/opt/spark/conf/metrics.properties
      - ${AIRFLOW_PROJ_DIR:-.}/monitoring/jmx_exporter/spark-metrics.yml:/opt/spark/jmx_exporter/config.yml
      - ${AIRFLOW_PROJ_DIR:-.}/monitoring/jmx_exporter/lib/jmx_prometheus_javaagent.jar:/opt/spark/jmx_exporter/jmx_prometheus_javaagent.jar
    networks:
      - realtimeflow

  spark-worker-1:
    build:
      context: .
      dockerfile: Dockerfile.spark
    image: custom-spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_OPTS: "-Dspark.metrics.conf=/opt/spark/conf/metrics.properties -javaagent:/opt/spark/jmx_exporter/jmx_prometheus_javaagent.jar=9095:/opt/spark/jmx_exporter/config.yml"
    ports:
      - "9095:9095"
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}/spark_streaming:/opt/spark/spark_streaming
      - ${AIRFLOW_PROJ_DIR:-.}/constants:/opt/spark/constants
      - ${AIRFLOW_PROJ_DIR:-.}/monitoring/spark/metrics.properties:/opt/spark/conf/metrics.properties
      - ${AIRFLOW_PROJ_DIR:-.}/monitoring/jmx_exporter/spark-metrics.yml:/opt/spark/jmx_exporter/config.yml
      - ${AIRFLOW_PROJ_DIR:-.}/monitoring/jmx_exporter/lib/jmx_prometheus_javaagent.jar:/opt/spark/jmx_exporter/jmx_prometheus_javaagent.jar
    networks:
      - realtimeflow

  spark-worker-2:
    build:
      context: .
      dockerfile: Dockerfile.spark
    image: custom-spark:latest
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_OPTS: "-Dspark.metrics.conf=/opt/spark/conf/metrics.properties -javaagent:/opt/spark/jmx_exporter/jmx_prometheus_javaagent.jar=9096:/opt/spark/jmx_exporter/config.yml"
    ports:
      - "9096:9096"
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}/spark_streaming:/opt/spark/spark_streaming
      - ${AIRFLOW_PROJ_DIR:-.}/constants:/opt/spark/constants
      - ${AIRFLOW_PROJ_DIR:-.}/monitoring/spark/metrics.properties:/opt/spark/conf/metrics.properties
      - ${AIRFLOW_PROJ_DIR:-.}/monitoring/jmx_exporter/spark-metrics.yml:/opt/spark/jmx_exporter/config.yml
      - ${AIRFLOW_PROJ_DIR:-.}/monitoring/jmx_exporter/lib/jmx_prometheus_javaagent.jar:/opt/spark/jmx_exporter/jmx_prometheus_javaagent.jar
    networks:
      - realtimeflow

  cassandra_db:
    image: cassandra:4.0.13
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=100M
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra
    networks:
      - realtimeflow


#Monitoring Section
  prometheus:
    image: prom/prometheus:v3.0.0
    container_name: prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    depends_on:
      - broker
    networks:
      - realtimeflow

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    networks:
      - realtimeflow


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - realtimeflow



networks:
  realtimeflow:
    driver: bridge


volumes:
  grafana-data:
  postgres-db-volume:
